export const actions = {
  LOADED_DATA: 'LOADED_DATA',
  LOADING_DATA: 'LOADING_DATA',
  ERROR_LOADING_DATA: 'ERROR_LOADING_DATA',
  SELECT_COUNTRY: 'SELECT_COUNTRY',
  CLEAR_SELECTION: 'CLEAR_SELECTION'
}